### ISSUE TITLE
Django 1.11 has reached the end of extended support

### ISSUE THREAD

**Issue by rbreslow** [azavea/docker-django#107]
Should we remove this version from the build matrix? Or continue maintaining it so the underlying OS can receive security updates? When are we going to start supporting Django 3.x?

This issue is to answer these questions and outline next steps (or confirm the lack there of).

See: https://www.djangoproject.com/weblog/2020/apr/01/bugfix-releases/

**Comment by hectcastro** [comment]
I think it makes sense to keep 1.11 in the build matrix until our org-wide usage of 1.11 diminishes further.

Regarding Django 3.x, I don't expect that we'll add support until 3.2 is released (the next LTS). The primary exception to that would be if a project comes around that has specific requirements depending features only available in 3.x.

**Comment by rbreslow** [comment]
We should also look through all the repositories that are using Django 1.11 (now deprecated) and open issues to let folks know we're in this situation now.

**Comment by coalkettler** [comment]
☝🏻 I've set up issues to track this in all actively developed / deployed repositories in our organizations.
