### ISSUE TITLE
Add different versions of PostgreSQL to the build matrix

### ISSUE THREAD

**Issue by rbreslow** [azavea/docker-django#163]
Right now, we're building this container image with a single version of the PostgreSQL client libraries for 11.x. This is problematic, as we maintain a wide array of PostgreSQL versions in production (9.x, 11.x, 12.x, and now, 13.x). 

We generally have very modest data storage and query requirements, which is why I'm guessing we haven't run into any friction. Still, there's a large amount of risk in utilizing potentially incompatible library versions.

`psql` complains about this, e.g.:

```
WARNING: psql major version 11, server major version 13.
         Some psql features might not work.
```

We should consider the following steps to mitigate risk:

- [ ] Extend `cipublish` to tag image with PostgreSQL client library version
- [ ] Extend build matrix to achieve parity with the [docker-postgis matrix](https://github.com/azavea/docker-postgis/blob/d65b5daf3ffe4ff65b15539879621e6bd7317e0c/.github/workflows/continuous_integration.yml#L15-L33)
- [ ] Extend Dockerfiles to support the PGDG archive APT repository, if necessary to achieve build matrix parity. (See: https://github.com/azavea/docker-postgis/pull/28/commits/19514e9cfff807972bb373c20ad5cb027ae4b611).

**Comment by BryanQuigley** [comment]
defaulting to 13 only in latest PR

**Comment by rbreslow** [comment]
A subtle thing in this issue is that we're running different versions of the PostgreSQL/PostGIS client libraries than RDS uses, even within a major version like 13.x. 

This issue was an extension of the work done in https://github.com/azavea/docker-postgis/pull/28, where we resolved the problem for the PostGIS container image.

**Comment by BryanQuigley** [comment]
Appreciate the heads up!
