### ISSUE TITLE
Add Python 3 support

### ISSUE THREAD

**Issue by CloudNiner** [azavea/docker-django#18]
It looks like there are a few ways to go about this:
- Add a separate Dockerfile to this repo that extends `python:3.6-slim` instead of `python:2.7-slim`
- Create a separate repo that extends from `python:3.6-slim`.

I don't see how to sensibly swap out only the FROM instruction in the base Dockerfile provided in this repo without an almost duplicate Dockerfile. Maybe there's something clever though that I don't see given my limited Docker experience.

Thoughts @hectcastro ?

**Comment by hectcastro** [comment]
I think that the best thing to do is to mimic what's going on [here](https://github.com/docker-library/python), although it isn't super clear what actually _is_ going on.

Regardless, I think the high level idea of housing multiple `Dockerfiles` inside of one repository (possibly with a template to help avoid from repeating ourselves) makes sense. I also think this'll break the current association we have with Git tags and Docker image tags.
