### ISSUE TITLE
Consider adding Django 2.1 to release matrix

### ISSUE THREAD

**Issue by hectcastro** [azavea/docker-django#59]
Django 2.1 was released today (8/1). Consider adding it to the published images set.

Considerations:

- Will we use it internally?
- Is it an LTS?

**Comment by tnation14** [comment]
I don't think publishing a 2.1 image is necessary. According to https://www.djangoproject.com/download/#supported-versions, the next LTS (2.2) comes out in 6 months, and 2.0 (which we currently publish) is supported until then. Any application that's going into production now should use the current LTS, and internal service that needs 2.x can use 2.0 until 2.2 is released.
