### ISSUE TITLE
Add image for Django 3.0

### ISSUE THREAD

**Issue by coalkettler** [azavea/docker-django#95]
Django 3.0 was recently released ([release notes](https://docs.djangoproject.com/en/3.0/releases/3.0/)). We should consider adding an image variant to support it, which will be the mainstream release until August 2020 and will receive extended support until April 2021 ([Django release timeline](https://www.djangoproject.com/download/#supported-versions)).

Django 3.0 supports the following Python versions ([see table in release notes](https://docs.djangoproject.com/en/3.0/releases/3.0/#python-compatibility)):
* 3.6
* 3.7
* 3.8

**Comment by hectcastro** [comment]
We've been working to standardize on bypassing support for non-LTS releases when possible. This is why we didn't add Django 2.1 to the matrix. We did add 2.0, but I believe that was influenced by an external project requirement.

**Comment by coalkettler** [comment]
Makes sense. Thanks for explaining!
